[package]
name = "biscuit-wasm-go"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
wasm-bindgen = "0.2.100"
biscuit-wasm = {git = "https://github.com/eclipse-biscuit/biscuit-wasm.git", rev = "2dc0467c07d85f8044bbb202c79a724f9aa8a1d7"}
serde-wasm-bindgen = "0.6.5"
#biscuit-wasm = {path = "/home/noa/Documents/projects/rust/biscuit-wasm"}

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
debug = true
debug-assertions = true