/* Automatically generated by wasm2c */
#ifndef WASM_PACK_H_GENERATED_
#define WASM_PACK_H_GENERATED_

#include "wasm-rt.h"

#include <stdint.h>

#ifndef WASM_RT_CORE_TYPES_DEFINED
#define WASM_RT_CORE_TYPES_DEFINED
typedef uint8_t u8;
typedef int8_t s8;
typedef uint16_t u16;
typedef int16_t s16;
typedef uint32_t u32;
typedef int32_t s32;
typedef uint64_t u64;
typedef int64_t s64;
typedef float f32;
typedef double f64;
#endif

#ifdef __cplusplus
extern "C" {
#endif

struct w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs;
struct w2c_0x2E0x2Fsnippets0x2Fbiscuit0x2Dauth0x2D314ca57174ae0e6d0x2Finline00x2Ejs;

typedef struct w2c_biscuit__wasm__go__bg {
  struct w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs* w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs_instance;
  struct w2c_0x2E0x2Fsnippets0x2Fbiscuit0x2Dauth0x2D314ca57174ae0e6d0x2Finline00x2Ejs* w2c_0x2E0x2Fsnippets0x2Fbiscuit0x2Dauth0x2D314ca57174ae0e6d0x2Finline00x2Ejs_instance;
  u32 w2c_g0;
  u32 w2c_g1;
  wasm_rt_memory_t w2c_memory;
  wasm_rt_funcref_table_t w2c_T0;
  wasm_rt_externref_table_t w2c_0x5F_wbindgen_export_4;
} w2c_biscuit__wasm__go__bg;

void wasm2c_biscuit__wasm__go__bg_instantiate(w2c_biscuit__wasm__go__bg*, struct w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs*, struct w2c_0x2E0x2Fsnippets0x2Fbiscuit0x2Dauth0x2D314ca57174ae0e6d0x2Finline00x2Ejs*);
void wasm2c_biscuit__wasm__go__bg_free(w2c_biscuit__wasm__go__bg*);
wasm_rt_func_type_t wasm2c_biscuit__wasm__go__bg_get_func_type(uint32_t param_count, uint32_t result_count, ...);

#ifndef wasm_multi_ii
#define wasm_multi_ii wasm_multi_ii
struct wasm_multi_ii {
  u32 i0;
  u32 i1;
};
#endif  /* wasm_multi_ii */

#ifndef wasm_multi_iii
#define wasm_multi_iii wasm_multi_iii
struct wasm_multi_iii {
  u32 i0;
  u32 i1;
  u32 i2;
};
#endif  /* wasm_multi_iii */

#ifndef wasm_multi_iiii
#define wasm_multi_iiii wasm_multi_iiii
struct wasm_multi_iiii {
  u32 i0;
  u32 i1;
  u32 i2;
  u32 i3;
};
#endif  /* wasm_multi_iiii */

/* import: '.\2Fbiscuit_wasm_go_bg.js' '__wbg_String_8f0eb39a4a4c2f66' */
void w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs_0x5F_wbg_String_8f0eb39a4a4c2f66(struct w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs*, u32, wasm_rt_externref_t);

/* import: '.\2Fbiscuit_wasm_go_bg.js' '__wbg_add_883d9432f9188ef2' */
wasm_rt_externref_t w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs_0x5F_wbg_add_883d9432f9188ef2(struct w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs*, wasm_rt_externref_t, wasm_rt_externref_t);

/* import: '.\2Fbiscuit_wasm_go_bg.js' '__wbg_buffer_609cc3eee51ed158' */
wasm_rt_externref_t w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs_0x5F_wbg_buffer_609cc3eee51ed158(struct w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs*, wasm_rt_externref_t);

/* import: '.\2Fbiscuit_wasm_go_bg.js' '__wbg_call_672a4d21634d4a24' */
wasm_rt_externref_t w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs_0x5F_wbg_call_672a4d21634d4a24(struct w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs*, wasm_rt_externref_t, wasm_rt_externref_t);

/* import: '.\2Fbiscuit_wasm_go_bg.js' '__wbg_call_7cccdd69e0791ae2' */
wasm_rt_externref_t w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs_0x5F_wbg_call_7cccdd69e0791ae2(struct w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs*, wasm_rt_externref_t, wasm_rt_externref_t, wasm_rt_externref_t);

/* import: '.\2Fbiscuit_wasm_go_bg.js' '__wbg_crypto_574e78ad8b13b65f' */
wasm_rt_externref_t w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs_0x5F_wbg_crypto_574e78ad8b13b65f(struct w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs*, wasm_rt_externref_t);

/* import: '.\2Fbiscuit_wasm_go_bg.js' '__wbg_debug_e17b51583ca6a632' */
void w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs_0x5F_wbg_debug_e17b51583ca6a632(struct w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs*, wasm_rt_externref_t, wasm_rt_externref_t, wasm_rt_externref_t, wasm_rt_externref_t);

/* import: '.\2Fbiscuit_wasm_go_bg.js' '__wbg_done_769e5ede4b31c67b' */
u32 w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs_0x5F_wbg_done_769e5ede4b31c67b(struct w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs*, wasm_rt_externref_t);

/* import: '.\2Fbiscuit_wasm_go_bg.js' '__wbg_entries_3265d4158b33e5dc' */
wasm_rt_externref_t w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs_0x5F_wbg_entries_3265d4158b33e5dc(struct w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs*, wasm_rt_externref_t);

/* import: '.\2Fbiscuit_wasm_go_bg.js' '__wbg_error_524f506f44df1645' */
void w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs_0x5F_wbg_error_524f506f44df1645(struct w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs*, wasm_rt_externref_t);

/* import: '.\2Fbiscuit_wasm_go_bg.js' '__wbg_error_7534b8e9a36f1ab4' */
void w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs_0x5F_wbg_error_7534b8e9a36f1ab4(struct w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs*, u32, u32);

/* import: '.\2Fbiscuit_wasm_go_bg.js' '__wbg_error_80de38b3f7cc3c3c' */
void w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs_0x5F_wbg_error_80de38b3f7cc3c3c(struct w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs*, wasm_rt_externref_t, wasm_rt_externref_t, wasm_rt_externref_t, wasm_rt_externref_t);

/* import: '.\2Fbiscuit_wasm_go_bg.js' '__wbg_fact_new' */
wasm_rt_externref_t w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs_0x5F_wbg_fact_new(struct w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs*, u32);

/* import: '.\2Fbiscuit_wasm_go_bg.js' '__wbg_getRandomValues_b8f5dbd5f3995a9e' */
void w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs_0x5F_wbg_getRandomValues_b8f5dbd5f3995a9e(struct w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs*, wasm_rt_externref_t, wasm_rt_externref_t);

/* import: '.\2Fbiscuit_wasm_go_bg.js' '__wbg_get_67b2ba62fc30de12' */
wasm_rt_externref_t w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs_0x5F_wbg_get_67b2ba62fc30de12(struct w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs*, wasm_rt_externref_t, wasm_rt_externref_t);

/* import: '.\2Fbiscuit_wasm_go_bg.js' '__wbg_get_b9b93047fe3cf45b' */
wasm_rt_externref_t w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs_0x5F_wbg_get_b9b93047fe3cf45b(struct w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs*, wasm_rt_externref_t, u32);

/* import: '.\2Fbiscuit_wasm_go_bg.js' '__wbg_getwithrefkey_1dc361bd10053bfe' */
wasm_rt_externref_t w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs_0x5F_wbg_getwithrefkey_1dc361bd10053bfe(struct w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs*, wasm_rt_externref_t, wasm_rt_externref_t);

/* import: '.\2Fbiscuit_wasm_go_bg.js' '__wbg_info_033d8b8a0838f1d3' */
void w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs_0x5F_wbg_info_033d8b8a0838f1d3(struct w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs*, wasm_rt_externref_t, wasm_rt_externref_t, wasm_rt_externref_t, wasm_rt_externref_t);

/* import: '.\2Fbiscuit_wasm_go_bg.js' '__wbg_instanceof_ArrayBuffer_e14585432e3737fc' */
u32 w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs_0x5F_wbg_instanceof_ArrayBuffer_e14585432e3737fc(struct w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs*, wasm_rt_externref_t);

/* import: '.\2Fbiscuit_wasm_go_bg.js' '__wbg_instanceof_Map_f3469ce2244d2430' */
u32 w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs_0x5F_wbg_instanceof_Map_f3469ce2244d2430(struct w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs*, wasm_rt_externref_t);

/* import: '.\2Fbiscuit_wasm_go_bg.js' '__wbg_instanceof_Uint8Array_17156bcf118086a9' */
u32 w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs_0x5F_wbg_instanceof_Uint8Array_17156bcf118086a9(struct w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs*, wasm_rt_externref_t);

/* import: '.\2Fbiscuit_wasm_go_bg.js' '__wbg_isArray_a1eab7e0d067391b' */
u32 w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs_0x5F_wbg_isArray_a1eab7e0d067391b(struct w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs*, wasm_rt_externref_t);

/* import: '.\2Fbiscuit_wasm_go_bg.js' '__wbg_isSafeInteger_343e2beeeece1bb0' */
u32 w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs_0x5F_wbg_isSafeInteger_343e2beeeece1bb0(struct w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs*, wasm_rt_externref_t);

/* import: '.\2Fbiscuit_wasm_go_bg.js' '__wbg_iterator_9a24c88df860dc65' */
wasm_rt_externref_t w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs_0x5F_wbg_iterator_9a24c88df860dc65(struct w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs*);

/* import: '.\2Fbiscuit_wasm_go_bg.js' '__wbg_length_a446193dc22c12f8' */
u32 w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs_0x5F_wbg_length_a446193dc22c12f8(struct w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs*, wasm_rt_externref_t);

/* import: '.\2Fbiscuit_wasm_go_bg.js' '__wbg_length_e2d2a49132c1b256' */
u32 w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs_0x5F_wbg_length_e2d2a49132c1b256(struct w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs*, wasm_rt_externref_t);

/* import: '.\2Fbiscuit_wasm_go_bg.js' '__wbg_log_6f0a4f74c31c9cb5' */
void w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs_0x5F_wbg_log_6f0a4f74c31c9cb5(struct w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs*, u32, u32);

/* import: '.\2Fbiscuit_wasm_go_bg.js' '__wbg_log_cad59bb680daec67' */
void w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs_0x5F_wbg_log_cad59bb680daec67(struct w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs*, wasm_rt_externref_t, wasm_rt_externref_t, wasm_rt_externref_t, wasm_rt_externref_t);

/* import: '.\2Fbiscuit_wasm_go_bg.js' '__wbg_msCrypto_a61aeb35a24c1329' */
wasm_rt_externref_t w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs_0x5F_wbg_msCrypto_a61aeb35a24c1329(struct w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs*, wasm_rt_externref_t);

/* import: '.\2Fbiscuit_wasm_go_bg.js' '__wbg_new_31a97dac4f10fab7' */
wasm_rt_externref_t w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs_0x5F_wbg_new_31a97dac4f10fab7(struct w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs*, wasm_rt_externref_t);

/* import: '.\2Fbiscuit_wasm_go_bg.js' '__wbg_new_405e22f390576ce2' */
wasm_rt_externref_t w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs_0x5F_wbg_new_405e22f390576ce2(struct w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs*);

/* import: '.\2Fbiscuit_wasm_go_bg.js' '__wbg_new_5e0be73521bc8c17' */
wasm_rt_externref_t w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs_0x5F_wbg_new_5e0be73521bc8c17(struct w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs*);

/* import: '.\2Fbiscuit_wasm_go_bg.js' '__wbg_new_78feb108b6472713' */
wasm_rt_externref_t w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs_0x5F_wbg_new_78feb108b6472713(struct w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs*);

/* import: '.\2Fbiscuit_wasm_go_bg.js' '__wbg_new_8a6f238a6ece86ea' */
wasm_rt_externref_t w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs_0x5F_wbg_new_8a6f238a6ece86ea(struct w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs*);

/* import: '.\2Fbiscuit_wasm_go_bg.js' '__wbg_new_a12002a7f91c75be' */
wasm_rt_externref_t w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs_0x5F_wbg_new_a12002a7f91c75be(struct w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs*, wasm_rt_externref_t);

/* import: '.\2Fbiscuit_wasm_go_bg.js' '__wbg_new_a239edaa1dc2968f' */
wasm_rt_externref_t w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs_0x5F_wbg_new_a239edaa1dc2968f(struct w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs*, wasm_rt_externref_t);

/* import: '.\2Fbiscuit_wasm_go_bg.js' '__wbg_newnoargs_105ed471475aaf50' */
wasm_rt_externref_t w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs_0x5F_wbg_newnoargs_105ed471475aaf50(struct w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs*, u32, u32);

/* import: '.\2Fbiscuit_wasm_go_bg.js' '__wbg_newwithbyteoffsetandlength_d97e637ebe145a9a' */
wasm_rt_externref_t w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs_0x5F_wbg_newwithbyteoffsetandlength_d97e637ebe145a9a(struct w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs*, wasm_rt_externref_t, u32, u32);

/* import: '.\2Fbiscuit_wasm_go_bg.js' '__wbg_newwithlength_a381634e90c276d4' */
wasm_rt_externref_t w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs_0x5F_wbg_newwithlength_a381634e90c276d4(struct w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs*, u32);

/* import: '.\2Fbiscuit_wasm_go_bg.js' '__wbg_next_25feadfc0913fea9' */
wasm_rt_externref_t w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs_0x5F_wbg_next_25feadfc0913fea9(struct w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs*, wasm_rt_externref_t);

/* import: '.\2Fbiscuit_wasm_go_bg.js' '__wbg_next_6574e1a8a62d1055' */
wasm_rt_externref_t w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs_0x5F_wbg_next_6574e1a8a62d1055(struct w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs*, wasm_rt_externref_t);

/* import: '.\2Fbiscuit_wasm_go_bg.js' '__wbg_node_905d3e251edff8a2' */
wasm_rt_externref_t w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs_0x5F_wbg_node_905d3e251edff8a2(struct w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs*, wasm_rt_externref_t);

/* import: '.\2Fbiscuit_wasm_go_bg.js' '__wbg_process_dc0fbacc7c1c06f7' */
wasm_rt_externref_t w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs_0x5F_wbg_process_dc0fbacc7c1c06f7(struct w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs*, wasm_rt_externref_t);

/* import: '.\2Fbiscuit_wasm_go_bg.js' '__wbg_publickey_unwrap' */
u32 w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs_0x5F_wbg_publickey_unwrap(struct w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs*, wasm_rt_externref_t);

/* import: '.\2Fbiscuit_wasm_go_bg.js' '__wbg_push_737cfc8c1432c2c6' */
u32 w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs_0x5F_wbg_push_737cfc8c1432c2c6(struct w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs*, wasm_rt_externref_t, wasm_rt_externref_t);

/* import: '.\2Fbiscuit_wasm_go_bg.js' '__wbg_randomFillSync_ac0988aba3254290' */
void w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs_0x5F_wbg_randomFillSync_ac0988aba3254290(struct w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs*, wasm_rt_externref_t, wasm_rt_externref_t);

/* import: '.\2Fbiscuit_wasm_go_bg.js' '__wbg_require_60cc747a6bc5215a' */
wasm_rt_externref_t w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs_0x5F_wbg_require_60cc747a6bc5215a(struct w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs*);

/* import: '.\2Fbiscuit_wasm_go_bg.js' '__wbg_setUTCFullYear_ccecb86f835fc949' */
f64 w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs_0x5F_wbg_setUTCFullYear_ccecb86f835fc949(struct w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs*, wasm_rt_externref_t, u32, u32, u32);

/* import: '.\2Fbiscuit_wasm_go_bg.js' '__wbg_setUTCHours_56b347a46c5ba182' */
f64 w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs_0x5F_wbg_setUTCHours_56b347a46c5ba182(struct w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs*, wasm_rt_externref_t, u32);

/* import: '.\2Fbiscuit_wasm_go_bg.js' '__wbg_setUTCMinutes_b74fa124314606d8' */
f64 w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs_0x5F_wbg_setUTCMinutes_b74fa124314606d8(struct w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs*, wasm_rt_externref_t, u32);

/* import: '.\2Fbiscuit_wasm_go_bg.js' '__wbg_setUTCSeconds_3162b526c0aa7b96' */
f64 w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs_0x5F_wbg_setUTCSeconds_3162b526c0aa7b96(struct w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs*, wasm_rt_externref_t, u32);

/* import: '.\2Fbiscuit_wasm_go_bg.js' '__wbg_set_37837023f3d740e8' */
void w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs_0x5F_wbg_set_37837023f3d740e8(struct w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs*, wasm_rt_externref_t, u32, wasm_rt_externref_t);

/* import: '.\2Fbiscuit_wasm_go_bg.js' '__wbg_set_3f1d0b984ed272ed' */
void w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs_0x5F_wbg_set_3f1d0b984ed272ed(struct w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs*, wasm_rt_externref_t, wasm_rt_externref_t, wasm_rt_externref_t);

/* import: '.\2Fbiscuit_wasm_go_bg.js' '__wbg_set_65595bdd868b3009' */
void w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs_0x5F_wbg_set_65595bdd868b3009(struct w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs*, wasm_rt_externref_t, wasm_rt_externref_t, u32);

/* import: '.\2Fbiscuit_wasm_go_bg.js' '__wbg_set_8fc6bf8a5b1071d1' */
wasm_rt_externref_t w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs_0x5F_wbg_set_8fc6bf8a5b1071d1(struct w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs*, wasm_rt_externref_t, wasm_rt_externref_t, wasm_rt_externref_t);

/* import: '.\2Fbiscuit_wasm_go_bg.js' '__wbg_stack_0ed75d68575b0f3c' */
void w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs_0x5F_wbg_stack_0ed75d68575b0f3c(struct w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs*, u32, wasm_rt_externref_t);

/* import: '.\2Fbiscuit_wasm_go_bg.js' '__wbg_static_accessor_GLOBAL_88a902d13a557d07' */
u32 w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs_0x5F_wbg_static_accessor_GLOBAL_88a902d13a557d07(struct w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs*);

/* import: '.\2Fbiscuit_wasm_go_bg.js' '__wbg_static_accessor_GLOBAL_THIS_56578be7e9f832b0' */
u32 w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs_0x5F_wbg_static_accessor_GLOBAL_THIS_56578be7e9f832b0(struct w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs*);

/* import: '.\2Fbiscuit_wasm_go_bg.js' '__wbg_static_accessor_SELF_37c5d418e4bf5819' */
u32 w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs_0x5F_wbg_static_accessor_SELF_37c5d418e4bf5819(struct w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs*);

/* import: '.\2Fbiscuit_wasm_go_bg.js' '__wbg_static_accessor_WINDOW_5de37043a91a9c40' */
u32 w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs_0x5F_wbg_static_accessor_WINDOW_5de37043a91a9c40(struct w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs*);

/* import: '.\2Fbiscuit_wasm_go_bg.js' '__wbg_subarray_aa9065fa9dc5df96' */
wasm_rt_externref_t w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs_0x5F_wbg_subarray_aa9065fa9dc5df96(struct w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs*, wasm_rt_externref_t, u32, u32);

/* import: '.\2Fbiscuit_wasm_go_bg.js' '__wbg_value_cd1ffa7b1ab794f1' */
wasm_rt_externref_t w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs_0x5F_wbg_value_cd1ffa7b1ab794f1(struct w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs*, wasm_rt_externref_t);

/* import: '.\2Fbiscuit_wasm_go_bg.js' '__wbg_versions_c01dfd4722a88165' */
wasm_rt_externref_t w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs_0x5F_wbg_versions_c01dfd4722a88165(struct w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs*, wasm_rt_externref_t);

/* import: '.\2Fbiscuit_wasm_go_bg.js' '__wbg_warn_aaf1f4664a035bd6' */
void w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs_0x5F_wbg_warn_aaf1f4664a035bd6(struct w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs*, wasm_rt_externref_t, wasm_rt_externref_t, wasm_rt_externref_t, wasm_rt_externref_t);

/* import: '.\2Fbiscuit_wasm_go_bg.js' '__wbindgen_as_number' */
f64 w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs_0x5F_wbindgen_as_number(struct w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs*, wasm_rt_externref_t);

/* import: '.\2Fbiscuit_wasm_go_bg.js' '__wbindgen_bigint_from_i64' */
wasm_rt_externref_t w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs_0x5F_wbindgen_bigint_from_i64(struct w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs*, u64);

/* import: '.\2Fbiscuit_wasm_go_bg.js' '__wbindgen_bigint_from_u64' */
wasm_rt_externref_t w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs_0x5F_wbindgen_bigint_from_u64(struct w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs*, u64);

/* import: '.\2Fbiscuit_wasm_go_bg.js' '__wbindgen_bigint_get_as_i64' */
void w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs_0x5F_wbindgen_bigint_get_as_i64(struct w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs*, u32, wasm_rt_externref_t);

/* import: '.\2Fbiscuit_wasm_go_bg.js' '__wbindgen_boolean_get' */
u32 w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs_0x5F_wbindgen_boolean_get(struct w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs*, wasm_rt_externref_t);

/* import: '.\2Fbiscuit_wasm_go_bg.js' '__wbindgen_copy_to_typed_array' */
void w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs_0x5F_wbindgen_copy_to_typed_array(struct w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs*, u32, u32, wasm_rt_externref_t);

/* import: '.\2Fbiscuit_wasm_go_bg.js' '__wbindgen_debug_string' */
void w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs_0x5F_wbindgen_debug_string(struct w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs*, u32, wasm_rt_externref_t);

/* import: '.\2Fbiscuit_wasm_go_bg.js' '__wbindgen_error_new' */
wasm_rt_externref_t w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs_0x5F_wbindgen_error_new(struct w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs*, u32, u32);

/* import: '.\2Fbiscuit_wasm_go_bg.js' '__wbindgen_in' */
u32 w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs_0x5F_wbindgen_in(struct w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs*, wasm_rt_externref_t, wasm_rt_externref_t);

/* import: '.\2Fbiscuit_wasm_go_bg.js' '__wbindgen_init_externref_table' */
void w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs_0x5F_wbindgen_init_externref_table(struct w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs*);

/* import: '.\2Fbiscuit_wasm_go_bg.js' '__wbindgen_is_bigint' */
u32 w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs_0x5F_wbindgen_is_bigint(struct w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs*, wasm_rt_externref_t);

/* import: '.\2Fbiscuit_wasm_go_bg.js' '__wbindgen_is_function' */
u32 w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs_0x5F_wbindgen_is_function(struct w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs*, wasm_rt_externref_t);

/* import: '.\2Fbiscuit_wasm_go_bg.js' '__wbindgen_is_object' */
u32 w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs_0x5F_wbindgen_is_object(struct w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs*, wasm_rt_externref_t);

/* import: '.\2Fbiscuit_wasm_go_bg.js' '__wbindgen_is_string' */
u32 w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs_0x5F_wbindgen_is_string(struct w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs*, wasm_rt_externref_t);

/* import: '.\2Fbiscuit_wasm_go_bg.js' '__wbindgen_is_undefined' */
u32 w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs_0x5F_wbindgen_is_undefined(struct w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs*, wasm_rt_externref_t);

/* import: '.\2Fbiscuit_wasm_go_bg.js' '__wbindgen_jsval_eq' */
u32 w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs_0x5F_wbindgen_jsval_eq(struct w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs*, wasm_rt_externref_t, wasm_rt_externref_t);

/* import: '.\2Fbiscuit_wasm_go_bg.js' '__wbindgen_jsval_loose_eq' */
u32 w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs_0x5F_wbindgen_jsval_loose_eq(struct w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs*, wasm_rt_externref_t, wasm_rt_externref_t);

/* import: '.\2Fbiscuit_wasm_go_bg.js' '__wbindgen_memory' */
wasm_rt_externref_t w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs_0x5F_wbindgen_memory(struct w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs*);

/* import: '.\2Fbiscuit_wasm_go_bg.js' '__wbindgen_number_get' */
void w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs_0x5F_wbindgen_number_get(struct w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs*, u32, wasm_rt_externref_t);

/* import: '.\2Fbiscuit_wasm_go_bg.js' '__wbindgen_number_new' */
wasm_rt_externref_t w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs_0x5F_wbindgen_number_new(struct w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs*, f64);

/* import: '.\2Fbiscuit_wasm_go_bg.js' '__wbindgen_string_get' */
void w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs_0x5F_wbindgen_string_get(struct w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs*, u32, wasm_rt_externref_t);

/* import: '.\2Fbiscuit_wasm_go_bg.js' '__wbindgen_string_new' */
wasm_rt_externref_t w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs_0x5F_wbindgen_string_new(struct w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs*, u32, u32);

/* import: '.\2Fbiscuit_wasm_go_bg.js' '__wbindgen_throw' */
void w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs_0x5F_wbindgen_throw(struct w2c_0x2E0x2Fbiscuit__wasm__go__bg0x2Ejs*, u32, u32);

/* import: '.\2Fsnippets\2Fbiscuit-auth-314ca57174ae0e6d\2Finline0.js' 'performance_now' */
f64 w2c_0x2E0x2Fsnippets0x2Fbiscuit0x2Dauth0x2D314ca57174ae0e6d0x2Finline00x2Ejs_performance_now(struct w2c_0x2E0x2Fsnippets0x2Fbiscuit0x2Dauth0x2D314ca57174ae0e6d0x2Finline00x2Ejs*);

/* export: 'memory' */
wasm_rt_memory_t* w2c_biscuit__wasm__go__bg_memory(w2c_biscuit__wasm__go__bg* instance);

/* export: 'publickey_ToString' */
struct wasm_multi_iiii w2c_biscuit__wasm__go__bg_publickey_ToString(w2c_biscuit__wasm__go__bg*, u32);

/* export: 'authorizer_getRunLimits' */
wasm_rt_externref_t w2c_biscuit__wasm__go__bg_authorizer_getRunLimits(w2c_biscuit__wasm__go__bg*, u64);

/* export: '__wbg_biscuitbuilder_free' */
void w2c_biscuit__wasm__go__bg_0x5F_wbg_biscuitbuilder_free(w2c_biscuit__wasm__go__bg*, u32, u32);

/* export: 'biscuitbuilder_new' */
u32 w2c_biscuit__wasm__go__bg_biscuitbuilder_new(w2c_biscuit__wasm__go__bg*);

/* export: 'biscuitbuilder_build' */
struct wasm_multi_iii w2c_biscuit__wasm__go__bg_biscuitbuilder_build(w2c_biscuit__wasm__go__bg*, u32, u32);

/* export: 'biscuitbuilder_merge' */
void w2c_biscuit__wasm__go__bg_biscuitbuilder_merge(w2c_biscuit__wasm__go__bg*, u32, u32);

/* export: 'biscuitbuilder_setRootKeyId' */
void w2c_biscuit__wasm__go__bg_biscuitbuilder_setRootKeyId(w2c_biscuit__wasm__go__bg*, u32, u32);

/* export: 'biscuitbuilder_addFact' */
struct wasm_multi_ii w2c_biscuit__wasm__go__bg_biscuitbuilder_addFact(w2c_biscuit__wasm__go__bg*, u32, u32);

/* export: 'biscuitbuilder_addRule' */
struct wasm_multi_ii w2c_biscuit__wasm__go__bg_biscuitbuilder_addRule(w2c_biscuit__wasm__go__bg*, u32, u32);

/* export: 'biscuitbuilder_addCheck' */
struct wasm_multi_ii w2c_biscuit__wasm__go__bg_biscuitbuilder_addCheck(w2c_biscuit__wasm__go__bg*, u32, u32);

/* export: 'biscuitbuilder_addCode' */
struct wasm_multi_ii w2c_biscuit__wasm__go__bg_biscuitbuilder_addCode(w2c_biscuit__wasm__go__bg*, u32, u32, u32);

/* export: 'biscuitbuilder_addCodeWithParameters' */
struct wasm_multi_ii w2c_biscuit__wasm__go__bg_biscuitbuilder_addCodeWithParameters(w2c_biscuit__wasm__go__bg*, u32, u32, u32, wasm_rt_externref_t, wasm_rt_externref_t);

/* export: 'biscuitbuilder_toString' */
struct wasm_multi_ii w2c_biscuit__wasm__go__bg_biscuitbuilder_toString(w2c_biscuit__wasm__go__bg*, u32);

/* export: '__wbg_blockbuilder_free' */
void w2c_biscuit__wasm__go__bg_0x5F_wbg_blockbuilder_free(w2c_biscuit__wasm__go__bg*, u32, u32);

/* export: 'blockbuilder_new' */
u32 w2c_biscuit__wasm__go__bg_blockbuilder_new(w2c_biscuit__wasm__go__bg*);

/* export: 'blockbuilder_addFact' */
struct wasm_multi_ii w2c_biscuit__wasm__go__bg_blockbuilder_addFact(w2c_biscuit__wasm__go__bg*, u32, u32);

/* export: 'blockbuilder_addRule' */
struct wasm_multi_ii w2c_biscuit__wasm__go__bg_blockbuilder_addRule(w2c_biscuit__wasm__go__bg*, u32, u32);

/* export: 'blockbuilder_addCheck' */
struct wasm_multi_ii w2c_biscuit__wasm__go__bg_blockbuilder_addCheck(w2c_biscuit__wasm__go__bg*, u32, u32);

/* export: 'blockbuilder_addCode' */
struct wasm_multi_ii w2c_biscuit__wasm__go__bg_blockbuilder_addCode(w2c_biscuit__wasm__go__bg*, u32, u32, u32);

/* export: 'blockbuilder_addCodeWithParameters' */
struct wasm_multi_ii w2c_biscuit__wasm__go__bg_blockbuilder_addCodeWithParameters(w2c_biscuit__wasm__go__bg*, u32, u32, u32, wasm_rt_externref_t, wasm_rt_externref_t);

/* export: 'blockbuilder_toString' */
struct wasm_multi_ii w2c_biscuit__wasm__go__bg_blockbuilder_toString(w2c_biscuit__wasm__go__bg*, u32);

/* export: '__wbg_fact_free' */
void w2c_biscuit__wasm__go__bg_0x5F_wbg_fact_free(w2c_biscuit__wasm__go__bg*, u32, u32);

/* export: 'fact_fromString' */
struct wasm_multi_iii w2c_biscuit__wasm__go__bg_fact_fromString(w2c_biscuit__wasm__go__bg*, u32, u32);

/* export: 'fact_unboundParameters' */
wasm_rt_externref_t w2c_biscuit__wasm__go__bg_fact_unboundParameters(w2c_biscuit__wasm__go__bg*, u32);

/* export: 'fact_set' */
struct wasm_multi_ii w2c_biscuit__wasm__go__bg_fact_set(w2c_biscuit__wasm__go__bg*, u32, u32, u32, wasm_rt_externref_t);

/* export: 'fact_toString' */
struct wasm_multi_ii w2c_biscuit__wasm__go__bg_fact_toString(w2c_biscuit__wasm__go__bg*, u32);

/* export: 'fact_terms' */
wasm_rt_externref_t w2c_biscuit__wasm__go__bg_fact_terms(w2c_biscuit__wasm__go__bg*, u32);

/* export: '__wbg_rule_free' */
void w2c_biscuit__wasm__go__bg_0x5F_wbg_rule_free(w2c_biscuit__wasm__go__bg*, u32, u32);

/* export: 'rule_fromString' */
struct wasm_multi_iii w2c_biscuit__wasm__go__bg_rule_fromString(w2c_biscuit__wasm__go__bg*, u32, u32);

/* export: 'rule_unboundParameters' */
wasm_rt_externref_t w2c_biscuit__wasm__go__bg_rule_unboundParameters(w2c_biscuit__wasm__go__bg*, u32);

/* export: 'rule_unboundScopeParameters' */
wasm_rt_externref_t w2c_biscuit__wasm__go__bg_rule_unboundScopeParameters(w2c_biscuit__wasm__go__bg*, u32);

/* export: 'rule_set' */
struct wasm_multi_ii w2c_biscuit__wasm__go__bg_rule_set(w2c_biscuit__wasm__go__bg*, u32, u32, u32, wasm_rt_externref_t);

/* export: 'rule_setScope' */
struct wasm_multi_ii w2c_biscuit__wasm__go__bg_rule_setScope(w2c_biscuit__wasm__go__bg*, u32, u32, u32, wasm_rt_externref_t);

/* export: 'rule_toString' */
struct wasm_multi_ii w2c_biscuit__wasm__go__bg_rule_toString(w2c_biscuit__wasm__go__bg*, u32);

/* export: '__wbg_check_free' */
void w2c_biscuit__wasm__go__bg_0x5F_wbg_check_free(w2c_biscuit__wasm__go__bg*, u32, u32);

/* export: 'check_fromString' */
struct wasm_multi_iii w2c_biscuit__wasm__go__bg_check_fromString(w2c_biscuit__wasm__go__bg*, u32, u32);

/* export: 'check_unboundParameters' */
wasm_rt_externref_t w2c_biscuit__wasm__go__bg_check_unboundParameters(w2c_biscuit__wasm__go__bg*, u32);

/* export: 'check_unboundScopeParameters' */
wasm_rt_externref_t w2c_biscuit__wasm__go__bg_check_unboundScopeParameters(w2c_biscuit__wasm__go__bg*, u32);

/* export: 'check_set' */
struct wasm_multi_ii w2c_biscuit__wasm__go__bg_check_set(w2c_biscuit__wasm__go__bg*, u32, u32, u32, wasm_rt_externref_t);

/* export: 'check_setScope' */
struct wasm_multi_ii w2c_biscuit__wasm__go__bg_check_setScope(w2c_biscuit__wasm__go__bg*, u32, u32, u32, wasm_rt_externref_t);

/* export: 'check_toString' */
struct wasm_multi_ii w2c_biscuit__wasm__go__bg_check_toString(w2c_biscuit__wasm__go__bg*, u32);

/* export: '__wbg_policy_free' */
void w2c_biscuit__wasm__go__bg_0x5F_wbg_policy_free(w2c_biscuit__wasm__go__bg*, u32, u32);

/* export: 'policy_fromString' */
struct wasm_multi_iii w2c_biscuit__wasm__go__bg_policy_fromString(w2c_biscuit__wasm__go__bg*, u32, u32);

/* export: 'policy_unboundParameters' */
wasm_rt_externref_t w2c_biscuit__wasm__go__bg_policy_unboundParameters(w2c_biscuit__wasm__go__bg*, u32);

/* export: 'policy_unboundScopeParameters' */
wasm_rt_externref_t w2c_biscuit__wasm__go__bg_policy_unboundScopeParameters(w2c_biscuit__wasm__go__bg*, u32);

/* export: 'policy_set' */
struct wasm_multi_ii w2c_biscuit__wasm__go__bg_policy_set(w2c_biscuit__wasm__go__bg*, u32, u32, u32, wasm_rt_externref_t);

/* export: 'policy_setScope' */
struct wasm_multi_ii w2c_biscuit__wasm__go__bg_policy_setScope(w2c_biscuit__wasm__go__bg*, u32, u32, u32, wasm_rt_externref_t);

/* export: 'policy_toString' */
struct wasm_multi_ii w2c_biscuit__wasm__go__bg_policy_toString(w2c_biscuit__wasm__go__bg*, u32);

/* export: '__wbg_biscuit_free' */
void w2c_biscuit__wasm__go__bg_0x5F_wbg_biscuit_free(w2c_biscuit__wasm__go__bg*, u32, u32);

/* export: 'biscuit_builder' */
u32 w2c_biscuit__wasm__go__bg_biscuit_builder(w2c_biscuit__wasm__go__bg*);

/* export: 'biscuit_block_builder' */
u32 w2c_biscuit__wasm__go__bg_biscuit_block_builder(w2c_biscuit__wasm__go__bg*);

/* export: 'biscuit_appendBlock' */
struct wasm_multi_iii w2c_biscuit__wasm__go__bg_biscuit_appendBlock(w2c_biscuit__wasm__go__bg*, u32, u32);

/* export: 'biscuit_getAuthorizer' */
struct wasm_multi_iii w2c_biscuit__wasm__go__bg_biscuit_getAuthorizer(w2c_biscuit__wasm__go__bg*, u32);

/* export: 'biscuit_sealToken' */
struct wasm_multi_iii w2c_biscuit__wasm__go__bg_biscuit_sealToken(w2c_biscuit__wasm__go__bg*, u32);

/* export: 'biscuit_fromBytes' */
struct wasm_multi_iii w2c_biscuit__wasm__go__bg_biscuit_fromBytes(w2c_biscuit__wasm__go__bg*, u32, u32, u32);

/* export: 'biscuit_fromBytesWithProvider' */
struct wasm_multi_iii w2c_biscuit__wasm__go__bg_biscuit_fromBytesWithProvider(w2c_biscuit__wasm__go__bg*, u32, u32, wasm_rt_externref_t);

/* export: 'biscuit_fromBase64' */
struct wasm_multi_iii w2c_biscuit__wasm__go__bg_biscuit_fromBase64(w2c_biscuit__wasm__go__bg*, u32, u32, u32);

/* export: 'biscuit_fromBase64WithProvider' */
struct wasm_multi_iii w2c_biscuit__wasm__go__bg_biscuit_fromBase64WithProvider(w2c_biscuit__wasm__go__bg*, u32, u32, wasm_rt_externref_t);

/* export: 'biscuit_toBytes' */
struct wasm_multi_iiii w2c_biscuit__wasm__go__bg_biscuit_toBytes(w2c_biscuit__wasm__go__bg*, u32);

/* export: 'biscuit_toBase64' */
struct wasm_multi_iiii w2c_biscuit__wasm__go__bg_biscuit_toBase64(w2c_biscuit__wasm__go__bg*, u32);

/* export: 'biscuit_getRevocationIdentifiers' */
struct wasm_multi_ii w2c_biscuit__wasm__go__bg_biscuit_getRevocationIdentifiers(w2c_biscuit__wasm__go__bg*, u32);

/* export: 'biscuit_countBlocks' */
u32 w2c_biscuit__wasm__go__bg_biscuit_countBlocks(w2c_biscuit__wasm__go__bg*, u32);

/* export: 'biscuit_getBlockSource' */
struct wasm_multi_iiii w2c_biscuit__wasm__go__bg_biscuit_getBlockSource(w2c_biscuit__wasm__go__bg*, u32, u32);

/* export: 'biscuit_getThirdPartyRequest' */
struct wasm_multi_iii w2c_biscuit__wasm__go__bg_biscuit_getThirdPartyRequest(w2c_biscuit__wasm__go__bg*, u32);

/* export: 'biscuit_appendThirdPartyBlock' */
struct wasm_multi_iii w2c_biscuit__wasm__go__bg_biscuit_appendThirdPartyBlock(w2c_biscuit__wasm__go__bg*, u32, u32, u32);

/* export: 'biscuit_toString' */
struct wasm_multi_ii w2c_biscuit__wasm__go__bg_biscuit_toString(w2c_biscuit__wasm__go__bg*, u32);

/* export: '__wbg_thirdpartyrequest_free' */
void w2c_biscuit__wasm__go__bg_0x5F_wbg_thirdpartyrequest_free(w2c_biscuit__wasm__go__bg*, u32, u32);

/* export: 'thirdpartyrequest_fromBytes' */
struct wasm_multi_iii w2c_biscuit__wasm__go__bg_thirdpartyrequest_fromBytes(w2c_biscuit__wasm__go__bg*, u32, u32);

/* export: 'thirdpartyrequest_fromBase64' */
struct wasm_multi_iii w2c_biscuit__wasm__go__bg_thirdpartyrequest_fromBase64(w2c_biscuit__wasm__go__bg*, u32, u32);

/* export: 'thirdpartyrequest_toBytes' */
struct wasm_multi_iiii w2c_biscuit__wasm__go__bg_thirdpartyrequest_toBytes(w2c_biscuit__wasm__go__bg*, u32);

/* export: 'thirdpartyrequest_toBase64' */
struct wasm_multi_iiii w2c_biscuit__wasm__go__bg_thirdpartyrequest_toBase64(w2c_biscuit__wasm__go__bg*, u32);

/* export: 'thirdpartyrequest_createBlock' */
struct wasm_multi_iii w2c_biscuit__wasm__go__bg_thirdpartyrequest_createBlock(w2c_biscuit__wasm__go__bg*, u32, u32, u32);

/* export: '__wbg_thirdpartyblock_free' */
void w2c_biscuit__wasm__go__bg_0x5F_wbg_thirdpartyblock_free(w2c_biscuit__wasm__go__bg*, u32, u32);

/* export: 'thirdpartyblock_fromBytes' */
struct wasm_multi_iii w2c_biscuit__wasm__go__bg_thirdpartyblock_fromBytes(w2c_biscuit__wasm__go__bg*, u32, u32);

/* export: 'thirdpartyblock_fromBase64' */
struct wasm_multi_iii w2c_biscuit__wasm__go__bg_thirdpartyblock_fromBase64(w2c_biscuit__wasm__go__bg*, u32, u32);

/* export: 'thirdpartyblock_toBytes' */
struct wasm_multi_iiii w2c_biscuit__wasm__go__bg_thirdpartyblock_toBytes(w2c_biscuit__wasm__go__bg*, u32);

/* export: 'thirdpartyblock_toBase64' */
struct wasm_multi_iiii w2c_biscuit__wasm__go__bg_thirdpartyblock_toBase64(w2c_biscuit__wasm__go__bg*, u32);

/* export: 'init' */
void w2c_biscuit__wasm__go__bg_init(w2c_biscuit__wasm__go__bg*);

/* export: '__wbg_authorizerbuilder_free' */
void w2c_biscuit__wasm__go__bg_0x5F_wbg_authorizerbuilder_free(w2c_biscuit__wasm__go__bg*, u32, u32);

/* export: 'authorizerbuilder_new' */
u32 w2c_biscuit__wasm__go__bg_authorizerbuilder_new(w2c_biscuit__wasm__go__bg*);

/* export: 'authorizerbuilder_buildAuthenticated' */
struct wasm_multi_iii w2c_biscuit__wasm__go__bg_authorizerbuilder_buildAuthenticated(w2c_biscuit__wasm__go__bg*, u32, u32);

/* export: 'authorizerbuilder_buildUnauthenticated' */
struct wasm_multi_iii w2c_biscuit__wasm__go__bg_authorizerbuilder_buildUnauthenticated(w2c_biscuit__wasm__go__bg*, u32);

/* export: 'authorizerbuilder_addFact' */
struct wasm_multi_ii w2c_biscuit__wasm__go__bg_authorizerbuilder_addFact(w2c_biscuit__wasm__go__bg*, u32, u32);

/* export: 'authorizerbuilder_addRule' */
struct wasm_multi_ii w2c_biscuit__wasm__go__bg_authorizerbuilder_addRule(w2c_biscuit__wasm__go__bg*, u32, u32);

/* export: 'authorizerbuilder_addCheck' */
struct wasm_multi_ii w2c_biscuit__wasm__go__bg_authorizerbuilder_addCheck(w2c_biscuit__wasm__go__bg*, u32, u32);

/* export: 'authorizerbuilder_addPolicy' */
struct wasm_multi_ii w2c_biscuit__wasm__go__bg_authorizerbuilder_addPolicy(w2c_biscuit__wasm__go__bg*, u32, u32);

/* export: 'authorizerbuilder_merge' */
void w2c_biscuit__wasm__go__bg_authorizerbuilder_merge(w2c_biscuit__wasm__go__bg*, u32, u32);

/* export: 'authorizerbuilder_mergeBlock' */
void w2c_biscuit__wasm__go__bg_authorizerbuilder_mergeBlock(w2c_biscuit__wasm__go__bg*, u32, u32);

/* export: 'authorizerbuilder_addCode' */
struct wasm_multi_ii w2c_biscuit__wasm__go__bg_authorizerbuilder_addCode(w2c_biscuit__wasm__go__bg*, u32, u32, u32);

/* export: 'authorizerbuilder_addCodeWithParameters' */
struct wasm_multi_ii w2c_biscuit__wasm__go__bg_authorizerbuilder_addCodeWithParameters(w2c_biscuit__wasm__go__bg*, u32, u32, u32, wasm_rt_externref_t, wasm_rt_externref_t);

/* export: 'authorizerbuilder_toString' */
struct wasm_multi_ii w2c_biscuit__wasm__go__bg_authorizerbuilder_toString(w2c_biscuit__wasm__go__bg*, u32);

/* export: '__wbg_authorizer_free' */
void w2c_biscuit__wasm__go__bg_0x5F_wbg_authorizer_free(w2c_biscuit__wasm__go__bg*, u32, u32);

/* export: 'authorizer_authorize' */
struct wasm_multi_iii w2c_biscuit__wasm__go__bg_authorizer_authorize(w2c_biscuit__wasm__go__bg*, u32);

/* export: 'authorizer_authorizeWithLimits' */
struct wasm_multi_iii w2c_biscuit__wasm__go__bg_authorizer_authorizeWithLimits(w2c_biscuit__wasm__go__bg*, u32, wasm_rt_externref_t);

/* export: 'authorizer_query' */
struct wasm_multi_iiii w2c_biscuit__wasm__go__bg_authorizer_query(w2c_biscuit__wasm__go__bg*, u32, u32);

/* export: 'authorizer_queryWithLimits' */
struct wasm_multi_iii w2c_biscuit__wasm__go__bg_authorizer_queryWithLimits(w2c_biscuit__wasm__go__bg*, u32, u32, wasm_rt_externref_t);

/* export: 'authorizer_toString' */
struct wasm_multi_ii w2c_biscuit__wasm__go__bg_authorizer_toString(w2c_biscuit__wasm__go__bg*, u32);

/* export: '__wbg_keypair_free' */
void w2c_biscuit__wasm__go__bg_0x5F_wbg_keypair_free(w2c_biscuit__wasm__go__bg*, u32, u32);

/* export: 'keypair_new' */
u32 w2c_biscuit__wasm__go__bg_keypair_new(w2c_biscuit__wasm__go__bg*, u32);

/* export: 'keypair_fromPrivateKey' */
u32 w2c_biscuit__wasm__go__bg_keypair_fromPrivateKey(w2c_biscuit__wasm__go__bg*, u32);

/* export: 'keypair_getPublicKey' */
u32 w2c_biscuit__wasm__go__bg_keypair_getPublicKey(w2c_biscuit__wasm__go__bg*, u32);

/* export: 'keypair_getPrivateKey' */
u32 w2c_biscuit__wasm__go__bg_keypair_getPrivateKey(w2c_biscuit__wasm__go__bg*, u32);

/* export: '__wbg_publickey_free' */
void w2c_biscuit__wasm__go__bg_0x5F_wbg_publickey_free(w2c_biscuit__wasm__go__bg*, u32, u32);

/* export: 'publickey_toBytes' */
struct wasm_multi_ii w2c_biscuit__wasm__go__bg_publickey_toBytes(w2c_biscuit__wasm__go__bg*, u32, u32, u32, wasm_rt_externref_t);

/* export: 'publickey_toString' */
struct wasm_multi_ii w2c_biscuit__wasm__go__bg_publickey_toString(w2c_biscuit__wasm__go__bg*, u32);

/* export: 'publickey_toDatalogParameter' */
struct wasm_multi_ii w2c_biscuit__wasm__go__bg_publickey_toDatalogParameter(w2c_biscuit__wasm__go__bg*, u32);

/* export: 'publickey_fromBytes' */
struct wasm_multi_iii w2c_biscuit__wasm__go__bg_publickey_fromBytes(w2c_biscuit__wasm__go__bg*, u32, u32, u32);

/* export: 'publickey_fromString' */
struct wasm_multi_iii w2c_biscuit__wasm__go__bg_publickey_fromString(w2c_biscuit__wasm__go__bg*, u32, u32, u32);

/* export: '__wbg_privatekey_free' */
void w2c_biscuit__wasm__go__bg_0x5F_wbg_privatekey_free(w2c_biscuit__wasm__go__bg*, u32, u32);

/* export: 'privatekey_toBytes' */
struct wasm_multi_ii w2c_biscuit__wasm__go__bg_privatekey_toBytes(w2c_biscuit__wasm__go__bg*, u32, u32, u32, wasm_rt_externref_t);

/* export: 'privatekey_toString' */
struct wasm_multi_ii w2c_biscuit__wasm__go__bg_privatekey_toString(w2c_biscuit__wasm__go__bg*, u32);

/* export: 'privatekey_fromBytes' */
struct wasm_multi_iii w2c_biscuit__wasm__go__bg_privatekey_fromBytes(w2c_biscuit__wasm__go__bg*, u32, u32, u32);

/* export: 'privatekey_fromString' */
struct wasm_multi_iii w2c_biscuit__wasm__go__bg_privatekey_fromString(w2c_biscuit__wasm__go__bg*, u32, u32);

/* export: '__wbindgen_malloc' */
u32 w2c_biscuit__wasm__go__bg_0x5F_wbindgen_malloc(w2c_biscuit__wasm__go__bg*, u32, u32);

/* export: '__wbindgen_realloc' */
u32 w2c_biscuit__wasm__go__bg_0x5F_wbindgen_realloc(w2c_biscuit__wasm__go__bg*, u32, u32, u32, u32);

/* export: '__wbindgen_exn_store' */
void w2c_biscuit__wasm__go__bg_0x5F_wbindgen_exn_store(w2c_biscuit__wasm__go__bg*, u32);

/* export: '__externref_table_alloc' */
u32 w2c_biscuit__wasm__go__bg_0x5F_externref_table_alloc(w2c_biscuit__wasm__go__bg*);

/* export: '__wbindgen_export_4' */
wasm_rt_externref_table_t* w2c_biscuit__wasm__go__bg_0x5F_wbindgen_export_4(w2c_biscuit__wasm__go__bg* instance);

/* export: '__wbindgen_free' */
void w2c_biscuit__wasm__go__bg_0x5F_wbindgen_free(w2c_biscuit__wasm__go__bg*, u32, u32, u32);

/* export: '__externref_table_dealloc' */
void w2c_biscuit__wasm__go__bg_0x5F_externref_table_dealloc(w2c_biscuit__wasm__go__bg*, u32);

/* export: '__externref_drop_slice' */
void w2c_biscuit__wasm__go__bg_0x5F_externref_drop_slice(w2c_biscuit__wasm__go__bg*, u32, u32);

/* export: '__wbindgen_start' */
void w2c_biscuit__wasm__go__bg_0x5F_wbindgen_start(w2c_biscuit__wasm__go__bg*);

#ifdef __cplusplus
}
#endif

#endif  /* WASM_PACK_H_GENERATED_ */
